// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUP3YrdyT1UC4F5Q-cbk_EXSIpxNWwdPY',
    appId: '1:186568790705:web:b4f169c97536936b960890',
    messagingSenderId: '186568790705',
    projectId: 'lab9-c9ce7',
    authDomain: 'lab9-c9ce7.firebaseapp.com',
    storageBucket: 'lab9-c9ce7.appspot.com',
    measurementId: 'G-S50VHWJ13L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoExNLfdnry_xTeQJQfrEcVgXms0bDBL0',
    appId: '1:186568790705:android:1f97e5fe4dbb9ae3960890',
    messagingSenderId: '186568790705',
    projectId: 'lab9-c9ce7',
    storageBucket: 'lab9-c9ce7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3-VdmvQrDDeHBiu7QtO_snHAUVT2DW6o',
    appId: '1:186568790705:ios:71a91922ae69afa3960890',
    messagingSenderId: '186568790705',
    projectId: 'lab9-c9ce7',
    storageBucket: 'lab9-c9ce7.appspot.com',
    iosClientId: '186568790705-u187ddgegjb7q53ifkvi52008bv5go43.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3-VdmvQrDDeHBiu7QtO_snHAUVT2DW6o',
    appId: '1:186568790705:ios:71a91922ae69afa3960890',
    messagingSenderId: '186568790705',
    projectId: 'lab9-c9ce7',
    storageBucket: 'lab9-c9ce7.appspot.com',
    iosClientId: '186568790705-u187ddgegjb7q53ifkvi52008bv5go43.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab9',
  );
}
